import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div style={{ minHeight: "60vh", backgroundColor: "rgb(68, 50, 50)" }}>
          {children}
        </div>
      </body>
    </html>
  );
}
