import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <p>This is HEADER</p>
        </header>
        {children}
        <footer>
          <p>This is FOOTER</p>
        </footer>
      </body>
    </html>
  );
}
