import Sidebar from "@/components/shared/Sidebar";

export const metadata = {
  title: "Nextjs Dashboard",
  description: "Generated by next app",
};

export default function dashboardLayout({ children }) {
  return (
    <div>
      <Sidebar />
      {children}
    </div>
  );
}
